# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensors.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rsensors.proto\x12\ngas_sensor\"\r\n\x0b\x44\x61taRequest\"U\n\x0c\x44\x61taResponse\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x10\n\x08gas_type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\t2L\n\nMonitoring\x12>\n\x07GasData\x12\x17.gas_sensor.DataRequest\x1a\x18.gas_sensor.DataResponse\"\x00\x62\x06proto3'
)


_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensors_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_DATAREQUEST']._serialized_start = 29
    _globals['_DATAREQUEST']._serialized_end = 42
    _globals['_DATARESPONSE']._serialized_start = 44
    _globals['_DATARESPONSE']._serialized_end = 129
    _globals['_MONITORING']._serialized_start = 131
    _globals['_MONITORING']._serialized_end = 207
# @@protoc_insertion_point(module_scope)
